<script lang="ts">
  // The record form is generated by @sjsf from the class definition in the JSON
  // Schema that gen-jsonschema writes, and drawn with its daisyUI 5 theme. The
  // helpers in utils/recordForm.ts prepare the schema and merge the result; this
  // component keeps the hand-built form's props, buttons and taxonomy file
  // choice, so CardHolder uses it unchanged.
  import { untrack } from 'svelte';
  import { Content, Form, createForm, setFormContext, type Schema } from '@sjsf/form';
  import '@sjsf/form/fields/extra/enum-include';
  import { createFocusOnFirstError } from '@sjsf/form/focus-on-first-error';
  import { createFormIdBuilder } from '@sjsf/form/id-builders/modern';
  import { createFormMerger } from '@sjsf/form/mergers/modern';
  import { resolver } from '@sjsf/form/resolvers/compat';
  import { translation } from '@sjsf/form/translations/en';
  import { addFormComponents, createFormValidator } from '@sjsf/ajv8-validator';
  import { theme } from '@sjsf/daisyui5-theme';
  import '@sjsf/daisyui5-theme/extra-widgets/textarea-include';
  import Button from '$components/ui/Button/Button.svelte';

  import { ENDPOINTS, TEXTAREA_FIELDS, YOUR_FILES } from '$lib/constants';
  import { FIELD_ENDPOINT_MAP_STATIC } from '$lib/states/filters.svelte';
  import { dataState } from '$states/data.svelte';
  import { endpoint } from '$states/endpoint.svelte';
  import type { NexusRecord } from '$types/yaml';
  import {
    APP_MANAGED_SLOTS,
    READ_ONLY_SLOTS,
    addSchemaFormats,
    applyTaxonomyFile,
    buildFormSchema,
    buildSavedRecord,
    buildUiSchema,
    cachedJsonSchema,
    formValueOf,
    loadJsonSchema,
    seedRecord,
    suggestedValues
  } from '$utils/recordForm';

  // Props
  let {
    fieldSchema = {}, // Computed fields of the endpoint: display order and taxonomy flag
    record = {} as NexusRecord, // Record data, can be empty
    mode = '', // Mode of the form (e.g., "add", "edit")
    onSave = () => {}, // Called with { detail: { record } } once the form validates
    onCancel = () => {}, // Callback for canceling the form
    onDelete = null // Optional for edit-mode
  } = $props();

  // The mapping slots point at records of the endpoint being edited.
  const MAPPING_SLOTS = [
    'broad_mappings',
    'close_mappings',
    'exact_mappings',
    'narrow_mappings',
    'related_mappings'
  ];
  // The form renders this until the JSON Schema has arrived.
  const PENDING_SCHEMA: Schema = { type: 'object' };

  const endpointConfig = $derived(ENDPOINTS.find((e) => e.key === endpoint.current));
  const displayFields: string[] = $derived(
    Array.isArray(fieldSchema?.displayFields) ? fieldSchema.displayFields : []
  );

  // The record to edit, seeded as the hand-built form seeded it. A change of
  // record, mode or endpoint seeds it again and resets the form.
  const seeded = $derived(
    seedRecord(
      record,
      mode,
      displayFields,
      endpointConfig?.type,
      new Date().toISOString().split('T')[0]
    )
  );

  // The taxonomy file the record is saved to. It starts from the seeded record
  // and can be changed in the select above the generated fields.
  let filenameKey = $derived((seeded._filenameKey as string | undefined) ?? '');

  // The JSON Schema the app already fetched for its field lists, kept by
  // utils/recordForm.ts once the first form has loaded it.
  const cachedSchema = cachedJsonSchema();
  let jsonSchema = $state.raw<Record<string, unknown> | undefined>(cachedSchema);
  let loadError = $state('');
  if (cachedSchema === undefined) {
    loadJsonSchema()
      .then((schema) => (jsonSchema = schema))
      .catch((error) => (loadError = error instanceof Error ? error.message : String(error)));
  }

  // The schema and UI schema for the endpoint's class. A new schema resets the
  // values in the form, so the loaded records and the curate mode are read
  // untracked: data that arrives while the form is open leaves the edits alone.
  const prepared = $derived.by(() => {
    if (!jsonSchema || !endpointConfig) {
      return undefined;
    }
    const current = endpointConfig.key;
    const currentId = mode === 'edit' && typeof seeded.id === 'string' ? seeded.id : undefined;
    const seededTaxonomy =
      typeof seeded.isDefinedByTaxonomy === 'string' ? seeded.isDefinedByTaxonomy : undefined;
    const fieldEndpoints: Record<string, string> = {
      ...FIELD_ENDPOINT_MAP_STATIC,
      ...Object.fromEntries(MAPPING_SLOTS.map((slot) => [slot, current]))
    };
    const suggestions = untrack(() => {
      const context = {
        fieldEndpoints,
        items: dataState.items,
        yourItems: dataState.yourItems,
        endpoint: current,
        currentId,
        taxonomy: endpoint.isCurateMode ? seededTaxonomy : undefined
      };
      return Object.fromEntries(
        Object.keys(fieldEndpoints).map((slot) => [slot, suggestedValues(slot, context)])
      );
    });
    const schema = buildFormSchema(jsonSchema, endpointConfig, {
      hidden: APP_MANAGED_SLOTS,
      readOnly: READ_ONLY_SLOTS,
      suggestions
    });
    if (schema === undefined) {
      return undefined;
    }
    const uiSchema = buildUiSchema(schema, { order: displayFields, textarea: TEXTAREA_FIELDS });
    return { schema, uiSchema };
  });

  const form = createForm<NexusRecord>({
    theme,
    translation,
    resolver,
    idBuilder: createFormIdBuilder,
    merger: createFormMerger,
    validator: (options) =>
      createFormValidator({
        ...options,
        ajvPlugins: (ajv) => addSchemaFormats(addFormComponents(ajv))
      }),
    get schema() {
      return prepared?.schema ?? PENDING_SCHEMA;
    },
    get uiSchema() {
      return prepared?.uiSchema;
    },
    get initialValue() {
      return prepared ? formValueOf(seeded, prepared.schema) : undefined;
    },
    onSubmit: (value) => save(value),
    onSubmitError: createFocusOnFirstError()
  });
  setFormContext(form);

  // Called by the form once the value validates against the schema.
  function save(value: NexusRecord) {
    if (!prepared) {
      return;
    }
    const merged = buildSavedRecord(seeded, value, prepared.schema);
    const saved = applyTaxonomyFile(
      merged,
      filenameKey,
      displayFields.includes('isDefinedByTaxonomy')
    );
    if (typeof onSave === 'function') {
      onSave({ detail: { record: saved } });
    }
  }
</script>

<!-- Content-only: CardHolder provides the card shell (background, border,
     accent, padding), so no nested card wrapper is rendered here. -->
<div class="text-center text-base font-medium text-green-700">
  {mode === 'add' ? 'Add New Record' : 'Edit Record'}
</div>

<!-- The schema decides what is valid, so the browser's own checks are off and
     every error appears under its field. -->
<div class="record-form w-full">
  <Form attributes={{ novalidate: true }}>
    <div class="flex w-full flex-row gap-3">
      <Button
        type="submit"
        variant="success"
        size="sm"
        className="flex-1 min-w-[100px]"
        disabled={!prepared}
      >
        Save
      </Button>
      <Button
        type="button"
        variant="edit"
        size="sm"
        className="flex-1 min-w-[100px]"
        on:click={() => onCancel()}
      >
        Cancel
      </Button>
      {#if mode === 'edit' && typeof onDelete === 'function'}
        <Button
          type="button"
          variant="curate"
          size="sm"
          className="flex-1 min-w-[100px]"
          on:click={onDelete}
        >
          Delete
        </Button>
      {/if}
    </div>

    <!-- The taxonomy file is not a slot of any class, so it stays outside the
         generated fields. It cannot change once a record is saved to a file. -->
    {#if fieldSchema.includesTaxonomyField}
      <fieldset class="fieldset gap-y-2">
        <label class="fieldset-legend" for="record-form-taxonomy-file">Taxonomy file *</label>
        {#if YOUR_FILES.length > 1}
          <select
            id="record-form-taxonomy-file"
            class="select w-full"
            value={filenameKey}
            disabled={mode === 'edit'}
            onchange={(e) => (filenameKey = e.currentTarget.value)}
          >
            <option value="" disabled>Select taxonomy...</option>
            {#each YOUR_FILES as tax (tax.key)}
              <option value={tax.key}>{tax.key}</option>
            {/each}
          </select>
        {:else}
          <input
            id="record-form-taxonomy-file"
            class="input w-full"
            type="text"
            value={YOUR_FILES[0]?.key}
            readonly
          />
        {/if}
        <p class="fieldset-label">The file under byo/data that the record is saved to.</p>
      </fieldset>
    {/if}

    {#if prepared}
      <Content />
    {:else if loadError}
      <p class="text-sm text-red-700">The form cannot be built: {loadError}</p>
    {:else if jsonSchema}
      <p class="text-sm text-red-700">
        The JSON Schema has no class for the {endpoint.current} endpoint.
      </p>
    {:else}
      <p class="text-sm text-gray-500">Loading the form...</p>
    {/if}
  </Form>
</div>

<style>
  /* The hand-built form drew its controls with the blue border of
     shared-input.css. The generated controls keep that look over the daisyUI
     defaults, so the form looks as it did. */
  .record-form :global(input.input),
  .record-form :global(select.select),
  .record-form :global(textarea.textarea) {
    border: 2px solid #2563eb;
    background: #f8fafc;
    color: #1e293b;
    font-weight: 500;
    box-shadow: 0 1px 4px 0 rgba(37, 99, 235, 0.7);
  }
  .record-form :global(input.input:focus),
  .record-form :global(select.select:focus),
  .record-form :global(textarea.textarea:focus) {
    outline: none;
    border-color: #d946ef;
    box-shadow: 0 0 0 2px #f0abfc55;
    background: #fff;
  }
  .record-form :global(input.input:read-only),
  .record-form :global(select.select:disabled) {
    cursor: not-allowed;
  }
</style>
